#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY ["TaxCalculation.csproj", "."]
COPY ["../TaxCalculation.Services/TaxCalculation.Services.csproj", "../TaxCalculation.Services/"]
COPY ["../TaxCalculation.Persistense/TaxCalculation.Persistent.csproj", "../TaxCalculation.Persistense/"]
COPY ["../TaxCalculation.Core/TaxCalculation.Core.csproj", "../TaxCalculation.Core/"]
RUN dotnet restore "./TaxCalculation.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "TaxCalculation.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "TaxCalculation.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "TaxCalculation.dll"]